issue 36: Update pravega snapshot version to latest from jcenter
pravega/hadoop-connectors pull request #37
Opened 2018-06-15 22:10 UTC by yangb8

2018-06-15 22:39 UTC, EronWright commented on src/test/java/io/pravega/connectors/hadoop/PravegaConnectorMiniYarnITCase.java
> +    @Ignore @Test // TODO: ignore it now since it only works with submodule build. Some dependencies need to be investigated.
Could you mention the issue # here ?

2018-06-15 22:48 UTC, yangb8 commented on src/test/java/io/pravega/connectors/hadoop/PravegaConnectorMiniYarnITCase.java
> +    @Ignore @Test // TODO: ignore it now since it only works with submodule build. Some dependencies need to be investigated.
please refer issue #38

2018-06-15 22:49 UTC, vijikarthi requested changes
The changes looks good to me. Please take care of the merge conflicts and also have an issue created to address the failing test case.

2018-06-15 23:13 UTC, EronWright approved these changes

2018-06-16 17:07 UTC, vijikarthi approved these changes

2018-06-16 17:35 UTC, merged